name: SonarCloud
on:
  push: { branches: [ "main", "master" ] }
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  test-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build & test (creates JaCoCo XML)
        run: mvn -B -DskipTests=false clean verify

      - name: Set SonarCloud New Code baseline (one-time)
        run: |
          # Set the baseline date
          curl -s -u "${{ secrets.SONAR_TOKEN }}:" -X POST \
            -d "component=ConstruccionYPruebas_ConstruccionYPruebas" \
            -d "key=sonar.leak.period" \
            -d "value=2025-08-28" \
            https://sonarcloud.io/api/settings/set
          # Tell Sonar the type is a date
          curl -s -u "${{ secrets.SONAR_TOKEN }}:" -X POST \
            -d "component=ConstruccionYPruebas_ConstruccionYPruebas" \
            -d "key=sonar.leak.period.type" \
            -d "value=date" \
            https://sonarcloud.io/api/settings/set

      - name: SonarCloud scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.organization=construccionypruebas
            -Dsonar.projectKey=ConstruccionYPruebas_ConstruccionYPruebas
            -Dsonar.sources=src/main/java
            -Dsonar.tests=src/test/java
            -Dsonar.java.binaries=target/classes
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
            -Dsonar.qualitygate.wait=true
