name: SonarCloud
on:
  push: { branches: [ "main", "master" ] }
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      # Ensure Java is present for the scanner
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: SonarCloud scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
